### ISSUE TITLE
how to get defaultengine.ini and defaultgame.ini from fortnite client

### ISSUE THREAD

**Issue by imReq** [lorpus/fnpaktrack#2]
how to get defaultengine.ini and defaultgame.ini from fortnite client? thanks for help

**Comment by imReq** [comment]
i have fortnite 1.7.1 update files and i need defaultgame.ini and defaultengine.ini

**Comment by lorpus** [comment]
since 1.7.1 is so ancient idk if the ini's are encrypted or aligned the same way but u can get an idea of how to read it urself by searching ue4's source for FileEntry.IsEncrypted()

if ur able to upload it somewhere or link to a dl i can try and get em myself
