### ISSUE TITLE
to add for next update

### ISSUE THREAD

**Issue by lorpus** [lorpus/fnpaktrack#3]
FSoftObjectPath string representation
display the StructName of a StructProperty in the tag list

**Comment by kavvson** [comment]
Would it be possible to display `(ArrayProperty)=[object]` or `(ArrayProperty)=[object] (inner: StructProperty)` data?

**Comment by lorpus** [comment]
yeah but i have to manually add each type. which ones exactly do you want me to look at

**Comment by kavvson** [comment]
Do you have a discord perhaps?

**Comment by lorpus** [comment]
> Do you have a discord perhaps?

its a-me markio#4256
